name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps: 
    - uses: actions/checkout@v2
    - uses: TG908/setup-swift@v0
      with:
        version: '5.1'
    - run: swift build

